#include "CMS80F231x.h"
#include <intrins.h>
#include "globalvar.h"
#include "eeprom.h"

//========================================================================================
// Читает из еепром байт данных по адресу eaddr.
//========================================================================================
uint8_t EEPROM_read_byte(uint16_t eaddr)
{
	MLOCK = 0xAA;	//flash unlock
	
	MADRL = lobyte(eaddr);
	MADRH = hibyte(eaddr);
	MCTRL = bin(00010001);	//читаю дату
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	MLOCK = 0x00;	//flash lock
	return (MDATA);
}

//========================================================================================
// Пишет в еепром байт данных по адресу eaddr в сектора sect = 512байт.
// В данном варианте закомментированные регистры не меняет!
// это сделано для ускорения операций с буферной записью, т.к. по одному байту
// записывать в данной реализации не предполагаю
//========================================================================================
void EEPROM_write_byte(uint16_t eaddr, uint8_t edata)
{
	MLOCK = 0xAA;	//flash unlock 
	MDATA = edata;
	MADRL = lobyte(eaddr);
	MADRH = hibyte(eaddr);
	MCTRL = bin(00011001);	//пишу дату
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	MLOCK = 0x00;	//flash lock
}

//========================================================================================
// стирает номер сектора в еепром.
//========================================================================================
void EEPROM_sector_erase (uint16_t eaddr)
{
	MLOCK = 0xAA;	//flash unlock
	
	MADRL = lobyte(eaddr);
	MADRH = hibyte(eaddr);
	MCTRL = bin(00011101);	//стираю сектор с адресом даты
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	_nop_();
	MLOCK = 0x00;	//flash lock
}

void EEPROM_DataInit( void )
{
	if (EEPROM_read_byte(0) == 0x01){
		cepb = 1;
	}else{
		cepb = 0;
	}
}

/*
22. Flash memory operation
Flash memory is divided into two blocks for users: program area and data area.
-The size of the program area is 16K*8Bit; the data area (Data Flash) is 1K*8Bit;
-The program space is divided into 32 sectors, one sector contains 512 bytes; 
the data area is a total of 2 sectors.
The memory is readable under normal working conditions. 
In addition, it can be indirectly addressed through the Special Function Register (SFR). 5 in total
The SFR register is used to access the program memory:
⚫ MCTRL
⚫ MDATA
⚫ MADRL
⚫ MADRH
⚫ MLOCK

Operating the memory module interface, 
the MDATA register forms a byte for storing 8-bit data to be read/written, 
the MADR  register stores the address of the MDATA unit being accessed.

The memory allows byte reads and writes. 
Byte write operation writes new data (erase before writing).
The write time is controlled by the on-chip timer.

The write and erase voltages are generated by the on-chip charge pump, 
which is rated to work within the voltage range of the device for byte operations.
Since the memory type is Flash, the erase operation only supports sector erasing, not byte erasing.

Before modifying the data of a certain address, it is recommended to save other data, 
erase the current sector, and then write data.
Through the memory module interface, 
the memory can be R/W/E operations, that is, read/write/erase operations.

Flash protection lock register MLOCK
0xFB Bit7 Bit6 Bit5 Bit4 Bit3 Bit2 Bit1 Bit0
MLOCK MLOCK7 MOCK6 MLOCK5 MLOCK4 MLOCK3 MLOCK2 MLOCK1 MLOCK0
读写 W W W W W W W W
复位 1 0 1 0 1 0 1 0
Bit7~Bit0 MLOCK<7:0>: Memory operation enable bit.
AAH: Allow memory related R/W/E operations
00H/FFH: Operation not allowed
Prohibit writing other values
(This register only supports write operation, read as 00H)

Flash memory data register MDATA
Bit7~Bit0 MDATA<7:0>: Data to read or write to the program memory.

Flash memory address register MADRL
0xFC Bit7 Bit6 Bit5 Bit4 Bit3 Bit2 Bit1 Bit0
MADRL MADRL7 MADRL6 MADRL5 MADRL4 MADRL3 MADRL2 MADRL1 MADRL0
读写 R/W R/W R/W R/W R/W R/W R/W R/W
复位值 0 0 1 1 1 1 1 1
Bit7~Bit0 MADRL<7:0>: Specify the lower 8 bits of the address for memory read/write operations.

Flash memory address register MADRH
0xFD Bit7 Bit6 Bit5 Bit4 Bit3 Bit2 Bit1 Bit0
MADRH MADRH7 MADRH6 MADRH5 MADRH4 MADRH3 MADRH2 MADRH1 MADRH0
读写 R/W R/W R/W R/W R/W R/W R/W R/W
复位值 0 0 0 0 0 0 0 0
Bit7~Bit0 MADRH<7:0>: Specify the upper 8 bits of the address for memory read/write operations.

Flash memory control register MCTRL
0xFF Bit7 Bit6 Bit5 Bit4 Bit3 Bit2 Bit1 Bit0
MCTRL - - MERR MREG MMODE1 MMODE0 - MSTART
Read and write R R R R/W R/W R/W R/W R/W
Reset value 0 0 0 1 0 0 0 0
Bit7~Bit6 -
Bit5 MERR: Operation error flag (write 0 to clear);
1= Before the programming operation starts, check that the data in the programming address 
is not "FFH" (not erased), and the write operation is terminated immediately.
0= -
Bit4 MREG: Flash area selection bit;
1= Select data area (the lower 10 bits of address are valid);
0= Select the program area (the lower 14-bit address is valid).
Bit3~ Bit2 MMODE<1:0>: Operation mode selection bits:
11= Erase operation mode (the range of erase operation is: the entire sector where the current address is located);
10 = write operation mode;
01 = reserved;
00 = Read operation mode.
Bit1 is not used and read as 0.
Bit0 MSTART: Operation start control bit;
1= Start program memory R/W/E operation (after the operation is completed, 
it can be automatically cleared by hardware);
0= Write: terminate or do not start program memory R/W/E operation;
Read: The operation is complete or the operation is not started.
When operating the Flash memory, the CPU is in a pause state, 
and when the operation is completed, the CPU continues to run instructions.
-The writing time is approximately: 
30us (including data detection time before writing, programming time, and end processing time)
-Reading time: 10*Tsys
-Sector erasing time is approximately: 4.6ms

6 NOP instructions must be followed by the operation memory instruction:
MOV MCTRL, #09H; start of write operation
NOP
NOP
NOP
NOP
NOP
NOP
MOV MCTRL, #01H; start of read operation
NOP
NOP
NOP
NOP
NOP
NOP

*/
